include: package:lints/recommended.yaml

linter:
  rules:
    - prefer_single_quotes
    - unawaited_futures
    - always_declare_return_types
    - lines_longer_than_80_chars: false

formatter:
  page_width: 100