analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    todo: ignore
  exclude:
    - flutter/**
    - lib/api/*.dart
    - .dart_tool

linter:
  rules:
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
