name: Dart CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        # Adding --fatal-infos ensures the highest code quality standards
        run: dart analyze --fatal-infos

      - name: Run tests
        run: dart test

      - name: Publish Dry Run
        # This ensures every PR is actually "publishable" to pub.dev
        run: dart pub publish --dry-run